import Head from "next/head";
import Link from "next/link";
import songs from "./songs.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="flex flex-col justify-center items-center gap-5 my-20">
          {songs.map((song) => {
            return (
              <Link key={song.number} href={`/hymn/${song.number}`}>
                <a>
                  #{song.number} - {song.name}
                </a>
              </Link>
            );
          })}
        </section>
      </main>
    </div>
  );
}
